import { APP_TITLE, PRACTICES, PROFILE_DIMS, SOLO, LEARNING_MODES, GRADES, loadState, saveState, freshState } from './ppm-data.js';
import { generatePPM, qualityCheck } from './ppm-engine.js';
import { downloadWord, openPreview } from './ppm-document.js';

let state = loadState();
let view = 'dashboard';
let generated = null;
let sidebarOpen = false;

const $ = (q, root = document) => root.querySelector(q);
const $$ = (q, root = document) => [...root.querySelectorAll(q)];
const esc = (v) => String(v ?? '').replace(/[&<>\"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', '"':'&quot;' }[c]));
const themePalette = {
  modern: { primary:'#2f80ed', soft:'#e8f3ff' },
  islami: { primary:'#15966d', soft:'#edf9f3' },
  cartoon: { primary:'#7c4be8', soft:'#f4efff' },
  minimal: { primary:'#52667a', soft:'#f5f7f9' }
};

function save(){ saveState(state); }
function toast(message){
  document.querySelector('.toast')?.remove();
  const el=document.createElement('div'); el.className='toast'; el.textContent=message;
  document.body.appendChild(el); setTimeout(()=>el.remove(),2200);
}
function nav(next){ view=next; sidebarOpen=false; render(); window.scrollTo({top:0,behavior:'smooth'}); }
function setTheme(name){
  state.theme=name; state.color=themePalette[name]?.primary || state.color || '#2f80ed'; save(); render();
}
function setColor(color){ state.color=color; save(); applyTheme(); }
function applyTheme(){
  document.documentElement.style.setProperty('--primary',state.color || '#2f80ed');
  document.documentElement.style.setProperty('--hero-a',themePalette[state.theme]?.soft || '#e8f3ff');
}
function qgate(){
  const q=qualityCheck(state);
  return `<div class="quality"><div class="quality-head"><div><span class="eyebrow">QUALITY GATE</span><h3>${q.ready?'Siap digenerate':'Lengkapi input wajib'}</h3></div><b class="quality-score">${q.score}%</b></div><div class="quality-grid">${Object.entries(q.checks).map(([k,v])=>`<div><span class="${v?'good':''}">${v?'✓':'○'}</span>${esc(k)}</div>`).join('')}</div></div>`;
}
function heroArt(){
  return `<svg viewBox="0 0 420 220" role="img" aria-label="Ilustrasi pendidikan"><defs><linearGradient id="heroGradient" x1="0" x2="1"><stop offset="0" stop-color="#8bcfff"/><stop offset="1" stop-color="#a9efd6"/></linearGradient></defs><rect width="420" height="220" rx="28" fill="url(#heroGradient)"/><circle cx="48" cy="45" r="23" fill="#ffd34d"/><rect x="298" y="34" width="55" height="78" rx="12" fill="#72cf53"/><rect x="324" y="94" width="48" height="18" rx="8" fill="#3c8fda"/><circle cx="190" cy="48" r="27" fill="#f3c19e"/><path d="M163 47q27-38 54 0" fill="#704128"/><rect x="158" y="83" width="68" height="69" rx="17" fill="#fff"/><rect x="171" y="95" width="42" height="6" rx="3" fill="#2f80ed"/><rect x="171" y="109" width="31" height="6" rx="3" fill="#88adca"/><circle cx="273" cy="152" r="25" fill="#f0bd96"/><path d="M247 149q27-40 52 0" fill="#168466"/><rect x="246" y="176" width="56" height="28" rx="12" fill="#15966d"/><text x="18" y="199" font-family="Arial" font-size="15" font-weight="700" fill="#175fc5">Belajar • Bermakna • Mendalam</text></svg>`;
}
function topNav(){
  const items=[['dashboard','⌂','Dashboard'],['generator','📄','Buat PPM Baru'],['school','🏫','Data Sekolah/Madrasah'],['teacher','👥','Data Guru'],['curriculum','📚','Kurikulum & CP'],['atp','🎯','TP & ATP'],['deep','🧠','Deep Learning'],['solo','🧩','Taksonomi SOLO'],['profiles','🌟','Profil Lulusan'],['assessment','✅','Asesmen & Penilaian'],['themes','🎨','Template & Desain'],['illustration','🖼️','Gambar & Ilustrasi'],['documents','📁','Dokumen Saya'],['settings','⚙️','Pengaturan']];
  return items.map(([id,icon,label])=>`<button class="nav-item ${view===id?'active':''}" data-nav="${id}"><span>${icon}</span><b>${label}</b></button>`).join('');
}
function rail(){
  return `<section class="rail-card"><h3>Statistik Saya</h3><div class="mini-stats"><div><b>${state.docs?.length||0}</b><span>PPM</span></div><div><b>${state.meetings||1}</b><span>Pertemuan</span></div><div><b>${state.profiles?.length||0}</b><span>Profil</span></div><div><b>${qualityCheck(state).score}%</b><span>Ready</span></div></div></section><section class="rail-card"><div class="section-head"><h3>Tema Aplikasi</h3><button class="link-button" data-nav="themes">Lihat Semua →</button></div><div class="theme-grid-small">${Object.keys(themePalette).map(t=>`<button class="theme-small ${state.theme===t?'selected':''}" data-theme="${t}">${t}</button>`).join('')}</div><div class="color-dots">${['#2f80ed','#15966d','#7c4be8','#f59e0b','#eb6fa8'].map(c=>`<button aria-label="Warna ${c}" data-color="${c}" style="background:${c}"></button>`).join('')}</div></section><section class="rail-card"><h3>Ilustrasi Cepat</h3><div class="quick-prompt">Guru dan siswa belajar ${esc(state.subject||'pembelajaran')} tentang ${esc(state.material||'materi')}.</div><button class="btn primary full-btn" data-nav="illustration">Buat Gambar</button></section><section class="rail-card"><h3>Dokumen Terbaru</h3>${(state.docs||[]).slice(0,4).map(d=>`<div class="recent-doc">📄 ${esc(d.name)} <small>${esc(d.date||'')}</small></div>`).join('')||'<p class="muted">Belum ada dokumen.</p>'}</section>`;
}
function shell(){
  document.body.className=`theme-${state.theme||'modern'}`;
  applyTheme();
  document.querySelector('#app').innerHTML=`<div class="app-shell"><aside class="sidebar ${sidebarOpen?'open':''}"><div class="brand"><div class="brand-mark">P</div><div><b>GENERATOR PPM</b><small>Mudah • Lengkap • Menarik • Profesional</small></div></div><div class="mode-tabs"><button class="active">🏫 DIKNAS</button><button>🕌 KEMENAG</button></div><nav>${topNav()}</nav><div class="side-promo"><b>📣 Pendidikan Hari Ini, Cerah untuk Masa Depan!</b><p>Perangkat pembelajaran lebih cepat, rapi, dan menarik.</p><span>👨‍🏫 👩‍🏫 📚</span></div></aside><main class="main"><header class="topbar"><button class="mobile-menu" id="drawer">☰</button><div class="search">🔎<input id="search" placeholder="Cari menu, template, atau dokumen..."></div><div class="grow"></div><button class="top-icon" data-action="notify">🔔</button><div class="profile"><div class="avatar">👨‍🏫</div><div><b>${esc(state.teacher||'Guru Pengguna')}</b><small>${esc(state.subject||'—')} • ${esc(state.jenjang||'—')}</small></div></div></header><div class="context"><button class="active">DIKNAS</button><button>KEMENAG</button></div><div id="view">${page()}</div></main><aside class="right-rail">${rail()}</aside><div class="overlay ${sidebarOpen?'active':''}" id="overlay"></div></div>`;
  bind();
}
function field(key,label,type='text',extra=''){return `<div class="field"><label>${label}</label><input data-bind="${key}" type="${type}" value="${esc(state[key])}" ${extra}></div>`;}
function area(key,label){return `<div class="field full"><label>${label}</label><textarea data-bind="${key}">${esc(state[key])}</textarea></div>`;}
function dashboard(){
  return `<section class="hero"><div class="hero-copy"><span class="eyebrow">PERENCANAAN PEMBELAJARAN MENDALAM</span><h1>${APP_TITLE}</h1><p>Bangun perangkat ajar yang runut: CP → TP → ATP → Prota → Prosem → Modul Ajar → LKPD → Asesmen → Rubrik.</p><div class="hero-actions"><button class="btn primary" data-nav="generator">＋ Buat PPM Baru</button><button class="btn white" data-nav="themes">🎨 Tema & Desain</button></div></div><div class="hero-art">${heroArt()}</div></section><div class="stats"><div><b>${state.docs?.length||0}</b><span>PPM Tersimpan</span></div><div><b>${state.meetings||1}</b><span>Pertemuan</span></div><div><b>${state.profiles?.length||0}</b><span>Dimensi Profil</span></div><div><b>${qualityCheck(state).score}%</b><span>Kesiapan</span></div></div><section class="section"><div class="section-head"><h2>Menu Utama</h2><span class="hint">Semua modul terhubung ke satu sumber data.</span></div><div class="menu-grid">${[['generator','📄','Buat PPM Baru'],['school','🏫','Satuan Pendidikan'],['teacher','👥','Data Guru'],['curriculum','📚','Kurikulum & CP'],['atp','🎯','TP & ATP'],['deep','🧠','Deep Learning'],['solo','🧩','Taksonomi SOLO'],['profiles','🌟','Profil Lulusan'],['assessment','✅','Asesmen'],['themes','🎨','Tema & Desain'],['illustration','🖼️','Gambar & Ilustrasi'],['documents','📁','Dokumen Saya']].map(([r,i,t])=>`<button class="menu-card" data-nav="${r}"><span>${i}</span><b>${t}</b></button>`).join('')}</div></section><section class="section two"><div class="panel"><h3>Pengaturan Aktif</h3><div class="mini-list"><div><span>Jenjang / Kelas</span><b>${esc(state.jenjang)} ${esc(state.kelas)}</b></div><div><span>Mapel</span><b>${esc(state.subject)}</b></div><div><span>Materi</span><b>${esc(state.material||'—')}</b></div><div><span>Durasi</span><b>${esc(state.duration)}</b></div></div></div><div class="panel callout"><h3>Output Profesional</h3><p>Lima tabel inti, kegiatan per pertemuan, teks rata kanan-kiri, A4, Arial 11, tanda tangan kiri/kanan.</p><button class="btn primary" data-nav="generator">Mulai Menyusun →</button></div></section>`;
}
function generator(){
  const meetingCount=Math.max(1,Number(state.meetings)||1);
  return `<section class="workspace"><div class="workspace-head"><div><span class="eyebrow">STUDIO PPM</span><h2>Buat Perencanaan Pembelajaran Mendalam</h2><p>Satu formulir utama. Sistem mengolahnya menjadi lima tabel PPM profesional.</p></div><span class="badge">${esc(state.jenjang)} • ${esc(state.kelas)}</span></div><div class="step-tabs"><button class="active">1 Input</button><button data-nav="meeting">2 Pengalaman Belajar</button><button data-nav="assessment">3 Asesmen</button><button data-nav="preview">4 Review</button></div><div class="form-grid">${field('school','Nama Satuan Pendidikan')}${field('teacher','Nama Guru')}${field('teacherNip','NIP Guru')}${field('principal','Nama Kepala Sekolah')}${field('principalNip','NIP Kepala Sekolah')}<div class="field"><label>Jenjang Pendidikan</label><select data-bind="jenjang">${Object.keys(GRADES).map(x=>`<option ${state.jenjang===x?'selected':''}>${x}</option>`).join('')}</select></div><div class="field"><label>Kelas</label><select data-bind="kelas">${GRADES[state.jenjang].map(x=>`<option ${state.kelas===x?'selected':''}>${x}</option>`).join('')}</select></div>${field('subject','Mata Pelajaran')}${field('year','Tahun Pelajaran')}${field('meetings','Jumlah Pertemuan','number','min="1" max="30"')}${field('duration','Durasi Setiap Pertemuan','text','placeholder="contoh: 2 × 35 menit"')}${field('regency','Nama Kabupaten')}${field('date','Tanggal Pembuatan','date')}${area('cp','Capaian Pembelajaran (CP)')}${area('tp','Tujuan Pembelajaran')}${area('material','Materi Pelajaran')}<div class="field full"><label>Semester</label><div class="segmented">${['Ganjil','Genap'].map(x=>`<button data-semester="${x}" class="${state.semester===x?'active':''}">${x}</button>`).join('')}</div></div><div class="field full"><label>Praktik Pedagogis per Pertemuan</label><div class="meeting-practices">${Array.from({length:meetingCount},(_,i)=>`<div class="meeting-row"><span>Pertemuan ${i+1}</span><select data-practice-index="${i}">${PRACTICES.map(x=>`<option ${state.practices[i]===x?'selected':''}>${x}</option>`).join('')}</select></div>`).join('')}</div></div><div class="field full"><label>Dimensi Profil Lulusan <span class="hint">(multi pilih)</span></label><div class="check-grid">${PROFILE_DIMS.map(x=>`<button type="button" data-profile="${x}" class="check-chip ${state.profiles.includes(x)?'selected':''}">${state.profiles.includes(x)?'✓ ':''}${x}</button>`).join('')}</div></div><div class="field full"><label>Target Taksonomi SOLO</label><div class="solo-select">${SOLO.map(x=>`<button type="button" data-solo="${x}" class="check-chip ${state.solo===x?'selected':''}">${state.solo===x?'✓ ':''}${x}</button>`).join('')}</div></div></div>${qgate()}<div class="action-row"><button class="btn primary xl" id="generate">⚡ Generate PPM Profesional</button><button class="btn white" data-action="previewDraft">👁 Preview Draft</button><button class="btn white" data-action="reset">↺ Reset Form</button></div></section>`;
}
function meetingPage(){ const p=generated||generatePPM(state); return `<section class="workspace"><div class="workspace-head"><div><span class="eyebrow">TABEL 4</span><h2>Pengalaman Belajar per Pertemuan</h2><p>${p.experience.length} pertemuan dibuat otomatis.</p></div><button class="btn primary" data-action="generateNow">Regenerate</button></div>${p.experience.map(x=>`<article class="meeting-card"><div class="meeting-head"><b>Pertemuan ${x.pertemuan}</b><span>${esc(x.subtopic)}</span><span class="badge">${esc(x.practice)}</span></div><div class="experience-grid"><div><b>Memahami</b><span class="mode-chip">${esc(x.memahami[0])}</span><p>${esc(x.memahami[1])}</p></div><div><b>Mengaplikasi</b><span class="mode-chip">${esc(x.mengaplikasi[0])}</span><p>${esc(x.mengaplikasi[1])}</p></div><div><b>Refleksi</b><span class="mode-chip">${esc(x.refleksi[0])}</span><p>${esc(x.refleksi[1])}</p></div></div></article>`).join('')}<div class="action-row"><button class="btn white" data-nav="generator">← Kembali ke Input</button><button class="btn primary" data-nav="preview">Lihat PPM Lengkap →</button></div></section>`; }
function assessment(){ const p=generated||generatePPM(state); return `<section class="workspace"><div class="workspace-head"><div><span class="eyebrow">TABEL 5</span><h2>Asesmen Pembelajaran</h2><p>Diagnostik, proses, dan akhir diselaraskan dengan TP.</p></div></div>${p.assessment.map(([h,b])=>`<div class="assessment-card"><h3>${esc(h)}</h3><p>${esc(b)}</p><div class="rubric"><span>Ketepatan konsep</span><span>Penalaran/strategi</span><span>Bukti & alasan</span><span>Komunikasi</span><span>Refleksi</span></div></div>`).join('')}<div class="action-row"><button class="btn primary" data-nav="preview">Preview Dokumen</button></div></section>`; }
function standard(title,body){return `<section class="workspace"><div class="workspace-head"><div><span class="eyebrow">MODUL</span><h2>${title}</h2></div></div>${body}</section>`;}
function school(){return standard('Data Satuan Pendidikan',`<div class="form-grid">${field('school','Nama Satuan Pendidikan')}${field('principal','Nama Kepala Sekolah')}${field('principalNip','NIP Kepala Sekolah')}${field('regency','Nama Kabupaten')}</div><div class="action-row"><button class="btn primary" data-action="saveView">Simpan</button><button class="btn white" data-nav="generator">Gunakan di PPM</button></div>`);}
function teacher(){return standard('Data Guru',`<div class="form-grid">${field('teacher','Nama Guru')}${field('teacherNip','NIP Guru')}${field('subject','Mata Pelajaran')}</div><div class="action-row"><button class="btn primary" data-action="saveView">Simpan</button><button class="btn white" data-nav="generator">Gunakan di PPM</button></div>`);}
function curriculum(){return standard('Kurikulum & CP',`${area('cp','Capaian Pembelajaran')}${area('tp','Tujuan Pembelajaran')}<div class="action-row"><button class="btn primary" data-action="saveView">Simpan</button><button class="btn white" data-nav="atp">Lanjut TP & ATP →</button></div>`);}
function atp(){const p=generated||generatePPM(state); return standard('TP & ATP',`<p class="muted">Urutan tujuan per pertemuan mengikuti jumlah pertemuan dan subtopik otomatis.</p><div class="data-table"><table><thead><tr><th>No</th><th>Subtopik</th><th>Praktik Pedagogis</th><th>TP Fokus</th><th>Durasi</th></tr></thead><tbody>${p.experience.map(x=>`<tr><td>${x.pertemuan}</td><td>${esc(x.subtopic)}</td><td>${esc(x.practice)}</td><td>${esc(state.tp)}</td><td>${esc(state.duration)}</td></tr>`).join('')}</tbody></table></div>`);}
function deep(){return standard('Deep Learning',`<div class="deep-cards">${LEARNING_MODES.map(x=>`<div><b>${x}</b><p>${x==='Berkesadaran'?'Peserta didik memahami tujuan, proses, strategi, dan kemajuannya.':x==='Bermakna'?'Konsep dikaitkan dengan konteks nyata dan pengalaman peserta didik.':'Aktivitas aktif, aman, menyenangkan, kolaboratif, dan memberi ruang pilihan.'}</p></div>`).join('')}</div><button class="btn primary" data-nav="generator">Terapkan ke PPM</button>`);}
function soloPage(){return standard('Taksonomi SOLO',`<p class="muted">Pilih tingkat kedalaman berpikir yang menjadi target utama.</p><div class="solo-cards">${SOLO.map(x=>`<button class="solo-card ${state.solo===x?'active':''}" data-solo="${x}"><b>${x}</b><span>${x==='Prestructural'?'Belum menunjukkan pemahaman bermakna.':x==='Unistructural'?'Satu aspek relevan.':x==='Multistructural'?'Beberapa aspek secara terpisah.':x==='Relational'?'Menghubungkan beberapa aspek menjadi satu kesatuan.':'Menggeneralisasi, mencipta, dan mentransfer.'}</span></button>`).join('')}</div><div class="action-row"><button class="btn primary" data-nav="generator">Gunakan pada PPM</button></div>`);}
function profiles(){return standard('Dimensi Profil Lulusan',`<p class="muted">Pilih satu atau beberapa dimensi yang relevan.</p><div class="check-grid">${PROFILE_DIMS.map(x=>`<button data-profile="${x}" class="check-chip ${state.profiles.includes(x)?'selected':''}">${state.profiles.includes(x)?'✓ ':''}${x}</button>`).join('')}</div>`);}
function themes(){return standard('Template & Desain',`<div class="theme-large">${Object.keys(themePalette).map(t=>`<button class="theme-option ${state.theme===t?'selected':''}" data-theme="${t}" style="--theme:${themePalette[t].primary}"><div></div><b>${t}</b></button>`).join('')}</div><div class="color-picker-row"><b>Warna utama</b><input id="colorInput" type="color" value="${esc(state.color)}"><button class="btn white" data-action="applyColor">Terapkan</button></div>`);}
function illustration(){return standard('Gambar & Ilustrasi',`<div class="quick-prompt">Tulis kebutuhan ilustrasi: ${esc(state.subject)} — ${esc(state.material||'materi pembelajaran')}</div><div class="illustration-grid"><div>👩‍🏫📐</div><div>👨‍🎓🔬</div><div>🧕📚</div></div><button class="btn primary" data-action="illustration">Buat Konsep Ilustrasi</button>`);}
function documents(){return standard('Dokumen Saya',`${(state.docs||[]).length?`<div>${state.docs.map((d,i)=>`<div class="recent-doc"><b>📄 ${esc(d.name)}</b> <span>${esc(d.date||'')}</span><button class="btn white" data-action="openSaved" data-index="${i}">Preview</button></div>`).join('')}</div>`:'<div class="empty">Belum ada dokumen. Generate PPM pertama Anda.</div>'}`);}
function settings(){return standard('Pengaturan',`<div class="settings-grid"><div><b>Nama aplikasi</b><p>${APP_TITLE}</p></div><div><b>Format</b><p>A4 • Arial 11 • Justify • Microsoft Word</p></div><div><b>Penyimpanan</b><p>Data tersimpan lokal di browser.</p></div><div><button class="btn white" data-action="resetAll">Reset Semua Data</button></div></div>`);}
function preview(){const p=generated||generatePPM(state);return standard('Preview PPM Profesional',`<div class="action-row"><button class="btn primary" data-action="download">⬇ Download Microsoft Word</button><button class="btn white" data-action="openPreview">👁 Preview Dokumen</button></div><div class="paper-preview"><div class="doc-cover"><span>PERENCANAAN PEMBELAJARAN MENDALAM (PPM)</span><h1>${esc(p.meta.subject)}</h1><h3>${esc(p.meta.material)}</h3><p>${esc(p.meta.school)}</p><p>${esc(p.meta.jenjang)} ${esc(p.meta.kelas)} • Semester ${esc(p.meta.semester)}</p><small>${APP_TITLE}</small></div><h3>Tabel 1. Identitas</h3>${tableHtml(p.identity)}<h3>Tabel 2. Identifikasi</h3>${tableHtml(p.identification)}<h3>Tabel 3. Desain Pembelajaran</h3>${tableHtml(p.design)}<h3>Tabel 4. Pengalaman Belajar</h3>${p.experience.map(x=>`<div class="preview-meeting"><b>Pertemuan ${x.pertemuan} — ${esc(x.subtopic)}</b>${tableHtml([['Praktik Pedagogis',x.practice],['Memahami',`${x.memahami[0]} — ${x.memahami[1]}`],['Mengaplikasi',`${x.mengaplikasi[0]} — ${x.mengaplikasi[1]}`],['Refleksi',`${x.refleksi[0]} — ${x.refleksi[1]}`]])}</div>`).join('')}<h3>Tabel 5. Asesmen Pembelajaran</h3>${tableHtml(p.assessment)}<p class="signature-date">${esc(p.signature.regency)}, ${esc(p.signature.date)}</p><div class="signatures"><div><b>Kepala Satuan Pendidikan (${esc(p.signature.principalSchool)})</b><div class="sign-space"></div><b>${esc(p.signature.principal)}</b><br>NIP ${esc(p.signature.principalNip)}</div><div><b>Guru Mata Pelajaran (${esc(p.signature.subject)})</b><div class="sign-space"></div><b>${esc(p.signature.teacher)}</b><br>NIP ${esc(p.signature.teacherNip)}</div></div></div>`);}
function tableHtml(rows){return `<table><tbody>${rows.map(([a,b])=>`<tr><th>${esc(a)}</th><td>${esc(b).replace(/\n/g,'<br>')}</td></tr>`).join('')}</tbody></table>`;}
function page(){const pages={dashboard,generator,meeting:meetingPage,assessment,school,teacher,curriculum,atp,deep,solo:soloPage,profiles,themes,illustration,documents,settings,preview};return (pages[view]||dashboard)();}
function bind(){
  $$('[data-nav]').forEach(el=>el.onclick=e=>{e.preventDefault();nav(el.dataset.nav);});
  $$('[data-theme]').forEach(el=>el.onclick=()=>setTheme(el.dataset.theme));
  $$('[data-color]').forEach(el=>el.onclick=()=>setColor(el.dataset.color));
  $$('[data-bind]').forEach(el=>el.onchange=el.oninput=()=>{const k=el.dataset.bind;if(k==='jenjang'){state.jenjang=el.value;state.kelas=GRADES[el.value][0];}else if(k==='meetings'){state.meetings=Math.max(1,Math.min(30,Number(el.value)||1));const base=state.practices?.[0]||PRACTICES[0];state.practices=Array.from({length:state.meetings},(_,i)=>state.practices[i]||base);}else state[k]=el.value;save();if(['jenjang','meetings'].includes(k))render();else applyTheme();});
  $$('[data-semester]').forEach(el=>el.onclick=()=>{state.semester=el.dataset.semester;save();render();});
  $$('[data-practice-index]').forEach(el=>el.onchange=()=>{state.practices[Number(el.dataset.practiceIndex)]=el.value;save();});
  $$('[data-profile]').forEach(el=>el.onclick=()=>{const v=el.dataset.profile;state.profiles=state.profiles.includes(v)?state.profiles.filter(x=>x!==v):[...state.profiles,v];save();render();});
  $$('[data-solo]').forEach(el=>el.onclick=()=>{state.solo=el.dataset.solo;save();render();});
  $('#generate')?.addEventListener('click',()=>{const q=qualityCheck(state);if(!q.ready){toast('Lengkapi semua input wajib terlebih dahulu.');return;}generated=generatePPM(state);state.docs=state.docs||[];state.docs.unshift({name:`PPM ${state.subject} — ${state.material}`,date:new Date().toLocaleDateString('id-ID')});state.route='preview';save();view='preview';render();});
  $$('[data-action]').forEach(el=>el.onclick=()=>action(el.dataset.action,el));
  $('#drawer')?.addEventListener('click',()=>{sidebarOpen=!sidebarOpen;render();});
  $('#overlay')?.addEventListener('click',()=>{sidebarOpen=false;render();});
  $('#search')?.addEventListener('input',e=>{const term=e.target.value.toLowerCase();$$('.nav-item').forEach(x=>x.classList.toggle('hidden',!x.textContent.toLowerCase().includes(term)));});
}
function action(type,el){
  if(type==='notify'){toast('Tidak ada notifikasi baru.');return;}
  if(type==='reset'){state=freshState();save();view='generator';render();return;}
  if(type==='resetAll'){state=freshState();save();view='dashboard';render();return;}
  if(type==='saveView'){save();toast('Data tersimpan.');return;}
  if(type==='previewDraft'){generated=generatePPM(state);view='preview';render();return;}
  if(type==='generateNow'){generated=generatePPM(state);view='meeting';render();return;}
  if(type==='download'){downloadWord(generated||generatePPM(state));return;}
  if(type==='openPreview'){openPreview(generated||generatePPM(state));return;}
  if(type==='openSaved'){generated=generatePPM(state);view='preview';render();return;}
  if(type==='applyColor'){const c=$('#colorInput')?.value;if(c)setColor(c);return;}
  if(type==='illustration'){toast('Konsep ilustrasi siap. Hubungkan generator gambar pada backend untuk produksi aset AI.');return;}
}
function render(){shell();}
render();
