import{routes,load,save,defaults}from'./v3-data.js';
import{quality,build,printHTML}from'./v3-engine.js';
import{dashboard,ppm,atp,assessment,soloPage,deepPage,kbcPage,templatesPage,preview,generic,esc}from'./v3-pages.js';
let s=load(),generated=null;const app=document.querySelector('#app'),$=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>[...r.querySelectorAll(q)];
const pages={dashboard:()=>dashboard(s),ppm:()=>ppm(s,quality(s)),atp:()=>atp(s),assessment:()=>assessment(s),solo:()=>soloPage(s),deep:()=>deepPage(s),kbc:()=>kbcPage(s),templates:()=>templatesPage(s),preview:()=>preview(s,generated),school:()=>generic('school',s),teacher:()=>generic('teacher',s),curriculum:()=>generic('curriculum',s),illustration:()=>generic('illustration',s),documents:()=>generic('documents',s),settings:()=>generic('settings',s)};
function toast(m){document.querySelector('.toast')?.remove();let x=document.createElement('div');x.className='toast';x.textContent=m;document.body.append(x);setTimeout(()=>x.remove(),2200)}
function applyTheme(){document.body.className=s.theme==='modern'?'':`theme-${s.theme}`;document.documentElement.style.setProperty('--primary',s.color)}
function nav(id){if(id==='kbc'&&s.mode!=='KEMENAG')return toast('KBC hanya tersedia pada mode KEMENAG');s.route=id;save(s);render()}
function shell(){app.innerHTML=`<div class="overlay" id="overlay"></div><div class="app-shell"><aside class="sidebar" id="sidebar"><div class="brand"><div class="brand-mark">P</div><div><div class="brand-title">GENERATOR PPM</div><div class="brand-sub">Mudah • Lengkap • Menarik • Profesional</div></div></div><div class="mode-switch"><button data-mode="DIKNAS" class="${s.mode==='DIKNAS'?'active d':''}">🏫 DIKNAS</button><button data-mode="KEMENAG" class="${s.mode==='KEMENAG'?'active k':''}">🕌 KEMENAG</button></div><nav>${routes.map(r=>r[3]==='kbc'&&s.mode!=='KEMENAG'?'':`<button class="nav-item ${s.route===r[0]?'active':''}" data-route="${r[0]}"><span>${r[2]}</span><strong>${esc(r[1])}</strong></button>`).join('')}</nav><div class="side-promo"><b>📣 Pendidikan Hari Ini, Cerah untuk Masa Depan!</b><p>Perangkat pembelajaran lebih cepat, rapi, dan menarik.</p><div class="side-art">👨‍🏫👩‍🏫📚</div></div></aside><main class="main"><header class="topbar"><button class="mobile-menu" data-action="drawer">☰</button><div class="search">🔎<input id="search" placeholder="Cari menu, template, atau dokumen..."></div><div class="grow"></div><button class="top-icon" data-action="notify">🔔</button><button class="top-icon" data-action="theme-cycle">☼</button><div class="profile"><div class="avatar">👨‍🏫</div><div><b>${esc(s.teacher)}</b><small>${esc(s.subject)} • ${s.mode}</small></div></div></header><div class="context"><button data-mode="DIKNAS" class="${s.mode==='DIKNAS'?'active d':''}">DIKNAS</button><button data-mode="KEMENAG" class="${s.mode==='KEMENAG'?'active k':''}">KEMENAG</button></div><div id="view"></div></main><aside class="right-rail">${rail()}</aside></div>`;bindShell();applyTheme();render()}
function rail(){return `<section class="rail-card"><h3>Statistik Saya</h3><select class="semester"><option>${esc(s.semester)}</option><option>Genap 2025/2026</option></select><div class="mini-stats"><div class="mini blue"><b>${12+s.docs.length}</b><small>PPM</small></div><div class="mini green"><b>6</b><small>LKPD</small></div><div class="mini purple"><b>48</b><small>Soal</small></div><div class="mini orange"><b>24</b><small>Siswa</small></div></div></section><section class="rail-card"><div class="section-head"><h3>Tema Aplikasi</h3><button class="rail-link" data-route="templates">Lihat Semua →</button></div><div class="theme-grid">${['modern','islami','cartoon','minimal'].map(t=>`<button class="theme-card ${t} ${s.theme===t?'selected':''}" data-theme="${t}"><span>${t}</span></button>`).join('')}</div><div class="color-row">${['#2f80ed','#19b77b','#7656e8','#ff9e3d','#eb6fa8'].map(c=>`<button class="color-dot" style="background:${c}" data-color="${c}"></button>`).join('')}<button class="custom-color" data-action="custom">Custom Warna</button><input id="railColor" type="color" hidden value="${s.color}"></div></section><section class="rail-card"><h3>🖼️ Ilustrasi Cepat</h3><div class="quick"><div class="quick-prompt">Siswa belajar matematika bangun ruang dengan gaya kartun edukatif.</div><button class="make-btn" data-route="illustration">Buat Gambar</button></div><div class="thumb-grid"><div>👩‍🏫📐</div><div>👨‍🎓🔬</div><div>🧕📚</div></div></section><section class="rail-card"><h3>Dokumen Terbaru</h3>${s.docs.slice(0,3).map(d=>`<p class="recent">📄 ${esc(d.name)}<small>${esc(d.date)}</small></p>`).join('')||'<p class="recent">Belum ada dokumen.</p>'}</section>`}
function bindShell(){document.addEventListener('click',click,{once:true});$$('[data-route]').forEach(x=>x.onclick=e=>{e.preventDefault();nav(x.dataset.route)});$$('[data-mode]').forEach(x=>x.onclick=()=>{s.mode=x.dataset.mode;if(s.mode!=='KEMENAG'&&s.route==='kbc')s.route='dashboard';save(s);shell()});$$('[data-theme]').forEach(x=>x.onclick=()=>{s.theme=x.dataset.theme;save(s);shell()});$$('[data-color]').forEach(x=>x.onclick=()=>{s.color=x.dataset.color;save(s);applyTheme()});$$('[data-action]').forEach(x=>x.onclick=()=>act(x.dataset.action));$('#overlay').onclick=close;$('#search').oninput=e=>$$('.nav-item').forEach(x=>x.classList.toggle('hidden',!x.textContent.toLowerCase().includes(e.target.value.toLowerCase())));$('#railColor').onchange=e=>{s.color=e.target.value;save(s);applyTheme()}}
function click(){}
function close(){$('#sidebar')?.classList.remove('open');$('#overlay')?.classList.remove('active')}
function act(a){if(a==='drawer'){$('#sidebar').classList.toggle('open');$('#overlay').classList.toggle('active')}if(a==='notify')toast('Tidak ada notifikasi baru.');if(a==='theme-cycle'){let a=['modern','islami','cartoon','minimal'];s.theme=a[(a.indexOf(s.theme)+1)%4];save(s);shell()}if(a==='custom')$('#railColor')?.click()}
function bindView(){const v=$('#view');$$('[data-route]',v).forEach(x=>x.onclick=()=>nav(x.dataset.route));$$('[data-field]',v).forEach(x=>x.oninput=()=>{s[x.dataset.field]=x.value;save(s)});$$('[data-solo]',v).forEach(x=>x.onclick=()=>{s.solo=x.dataset.solo;save(s);render()});$$('[data-dl]',v).forEach(x=>x.onclick=()=>{let a=x.dataset.dl;s.dl=s.dl.includes(a)?s.dl.filter(y=>y!==a):[...s.dl,a];save(s);render()});$$('[data-kbc]',v).forEach(x=>x.onclick=()=>{let a=x.dataset.kbc;s.kbc=s.kbc.includes(a)?s.kbc.filter(y=>y!==a):[...s.kbc,a];save(s);render()});$$('[data-assess]',v).forEach(x=>x.onclick=()=>{s.assess[x.dataset.assess]=!s.assess[x.dataset.assess];save(s);render()});$$('[data-weight]',v).forEach(x=>x.oninput=()=>{s.weights[x.dataset.weight]=Math.max(0,+x.value||0);save(s)});$('#add-atp',v)?.addEventListener('click',()=>{s.atp.push({id:Date.now(),tp:'Tujuan pembelajaran baru',materi:s.topic,solo:s.solo,jp:1});save(s);render()});$$('[data-delete-atp]',v).forEach(x=>x.onclick=()=>{s.atp=s.atp.filter(a=>String(a.id)!==x.dataset.deleteAtp);save(s);render()});$('#generate',v)?.addEventListener('click',()=>{let q=quality(s);if(q.score<80)return toast('Quality Gate belum 80%. Lengkapi data PPM.');generated=build(s);s.docs=[{name:`PPM ${s.subject} — ${s.topic}`,date:new Date().toLocaleDateString('id-ID')},...s.docs];s.route='preview';save(s);shell()});$('#print',v)?.addEventListener('click',()=>{let w=window.open('','_blank');if(!w)return toast('Izinkan popup browser.');w.document.write(printHTML(generated||build(s)));w.document.close();setTimeout(()=>w.print(),300)});$$('[data-theme]',v).forEach(x=>x.onclick=()=>{s.theme=x.dataset.theme;save(s);shell()});$$('[data-action]',v).forEach(x=>x.onclick=()=>act(x.dataset.action));$$('[data-doc]',v).forEach(x=>x.onclick=()=>nav('preview'));}
function render(){applyTheme();$('#view').innerHTML=(pages[s.route]||pages.dashboard)();bindView()}
shell();
